### ISSUE TITLE
Ever use WLED?

### ISSUE THREAD

**Issue by mermelmadness** [witnessmenow/ESP32-Trinity#18]
I tried asking this question on the Discord but didn't get a response.  Have you ever tried flashing WLED to your ESP32 Trinity board and have it control a HUB75 matrix?  If yes, were there any special roadblocks you had to overcome?

**Comment by jangrewe** [comment]
WLED is for  WS2812B-compatible LED strips, not these kind of matrixes.

**Comment by mermelmadness** [comment]
Actually, you can make it control HUB75 matrices using a different intermediary board.
