### ISSUE TITLE
Power Output

### ISSUE THREAD

**Issue by laserir** [witnessmenow/ESP32-Trinity#26]
Hi, I power the board with 5V 3A over USB. The output voltage (that is supposed to power the display) only reaches 1,6V. Am I missing something?

**Comment by witnessmenow** [comment]
Have you enabled the jumper for USB power?

"Powering the matrix panel using USB-C" section of this page

https://esp32trinity.com/setup.html

**Comment by witnessmenow** [comment]
What type of display are you trying to power or how many displays? What voltage do you see when there is no displays attached?

**Comment by laserir** [comment]
Believe it or not... faulty USB cable... so stupid, sorry to bother :D
